### ISSUE TITLE
Compression read error

### ISSUE THREAD

**Issue by spetruzza** [sci-visus/PIDX#30]
Replicate the error with the following:
Write with
mpirun -np 8 examples/idx_compression_write -g 64x64x64 -l 32x32x32 -t 1 -v 3 -f out_comp

Read with
mpirun -np 8 examples/idx_comession_read -g 64x64x64 -l 32x32x32 -t 0 -v 0 -f out_comp

Error: [pidx/core/PIDX_file_io/PIDX_file_io_blocking_write_read.c] [26] MPI_File_open() filename out_comp/time000000000/000.bin failed.

**Comment by sidharth87** [comment]
the error was in usage, pidx does not allow reading at varying bit rate (for now)
Also while reading, PIDX automatically parses if the data is compressed or not, if it is then it uncompresses, the user does not have to specify the compression strategy while reading.
